Repository jenkinsci/pipeline-stage-step-plugin, pull requests merged in 2021-12, with the labels that each got.

#23 Update plugin POM and BOM
  .mvn/extensions.xml
  pom.xml
Labels: dependencies

#25 Use container agent in `Jenkinsfile` and test with Java 11
  Jenkinsfile
Labels: internal

#31 Bump plugin parent POM from 4.31 to 4.32
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/StageStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/StageStepExecution.java
Labels: dependencies

#30 enable cd
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: internal

#34 update README
  README.md
Labels: documentation
